server:
  servlet:
    context-path: /api
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus,metrics"
      base-path: /manage
  endpoint:
    health:
      show-details: always

spring:
  jooq:
    sql-dialect: postgres
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}